### ISSUE TITLE
GreyboxFuzzing Chapter, AFLGoSchedule

### ISSUE THREAD

**Issue by MichaelLiuzzi** [uds-se/fuzzingbook#109]
Hi,

According to my understanding of your paper In your chapter on greybox fuzzing, specifically the class that implements the "AflGoSchedule,"  i don't see a relationship between the paper "Directed Greybox Fuzzing" and the class as implemented. In fact, it appears that 1/distance^x, where x is 1, seems to deliver a very similar success rate in finding valid strings.

It seems that the chapter implies normalizing the seed energy to the range of min->max values should boost more interesting seeds, but that does not appear to be the case. The paper seems to say that that this "normalization" has nothing to do with the increased effectiveness, but rather a power schedule based on simulated annealing, if I recall correctly from memory.

**Comment by mboehme** [comment]
Hi Michael, Welcome to the Fuzzing Book, and thanks for your interest in directed greybox fuzzing.

Can you elaborate? Did you find an error with the AFLGo paper or with the Fuzzing Book section on Directed Greybox Fuzzing?

**Comment by MichaelLiuzzi** [comment]
Hi @mboehme!

Thank you for all of your hard work. I’m sorry for not being clear.

What i was trying to say that the chapter that was written, greybox fuzzing, presents a power schedule called “AFLGo” that does not seem to correspond to what appears to be the contribution you offer in the directed fuzzing paper, which is an annealing based power schedule.  As far as i can tell, the power schedule as implemented in the chapter on greybox fuzzing is very similar to the power schedule 1/distance^x that was also implemented in that chapter. The primary power of the aflgo schedule in that chapter appears to be no exponent in the divisor, whereas the chapter text suggests it is because of the “normalization.” 

Does that make sense?

**Comment by mboehme** [comment]
It does :)

The key contribution of the AFLGo paper is the efficient integration of meta-heuristic search with greybox fuzzing. The objective is to minimize the distance to a set of targets. To maximize efficiency, we propose to move most of the program analysis needed to compute the fitness function to compile time. Personally, I see the proposed power schedules based on simulated annealing merely as examples of such an integration. To simplify the discussion in the Fuzzing Book and connect it nicely with the preceding sections, we might present a different schedule, but the fundamental idea is the same.

We invite you to use the code presented in the Fuzzing Book to compare with the schedules presented in the AFLGo paper, or better yet, to implement your own schedules. I'm sure, you might quickly find ways to improve on the one that is presented here. Let us know how it goes.

**Comment by MichaelLiuzzi** [comment]
thank you, i really appreciate your time :)

**Comment by mboehme** [comment]
Thanks Michael! 

Closing for now. You can re-open if you get any results :)
