### ISSUE TITLE
Broken navigation menu in the Code Coverage chapter

### ISSUE THREAD

**Issue by h4iku** [uds-se/fuzzingbook#122]
**Describe the bug**
The navigation bar doesn't work on the Code Coverage web page. It seems the synopsis code example is leaking into the menu items.

**To Reproduce**
1. Go to the [Code Coverage page](https://www.fuzzingbook.org/html/Coverage.html)
2. Check the navigation bar.

**Screenshot**
<img width="958" alt="menu" src="https://user-images.githubusercontent.com/3812788/151643020-bdae027f-a640-478b-9c25-67e024702ed3.png">

**Environment**
 - OS: Windows 10, Android, Pop!_OS
 - Browser: Firefox, Chrome

**Comment by andreas-zeller** [comment]
Thank you! This was due to our menu generation script mistaking code output `# 1`, `# 2`, etc. for Markdown titles, and is now fixed.
