### ISSUE TITLE
Book recommendation broken, "Software Testing: From Theory to Practice"

### ISSUE THREAD

**Issue by Qualadore** [uds-se/fuzzingbook#137]
https://www.fuzzingbook.org/html/Intro_Testing.html#Background

> An all-new modern, comprehensive, and online textbook on testing is ["Software Testing: From Theory to Practice"](https://sttp.site/) [[Maurício Aniche et al, 2020](https://sttp.site/)], available [online](https://sttp.site/). Much recommended!

The linked site now reads
> These lecture notes are not available anymore. They were replaced by my new book on software testing, [Effective Software Testing: A Developer's Guide](https://www.effective-software-testing.com/), published by Manning.

For anyone who may want to read it, I forked the repositories and reverted the deletion.
https://sttp-book-fork.github.io/

**Comment by andreas-zeller** [comment]
Thanks! Now fixed; this will also show on the Web pages with the next release.
