### ISSUE TITLE
The check_grammar method in ProbabilisticGrammarFuzzer raises an AssertionError when a customized start_symbol is used

### ISSUE THREAD

**Issue by yuzi-zly** [uds-se/fuzzingbook#179]
**Describe the bug**
The check_grammar method in ProbabilisticGrammarFuzzer raises an AssertionError when a customized start_symbol is used. This occurs because the statement "assert is_valid_probabilistic_grammar(self.grammar)" only passes self.grammar to is_valid_probabilistic_grammar, which internally defaults to using START_SYMBOL = "<start>", rather than the customized start_symbol provided by the user.

**To Reproduce**
1. Write a grammar which doesn't using "<start>" as start_symbol.
2. Create a ProbabilisticGrammarFuzzer instance with the defined grammar and a customized start_symbol (not the "<start>")

**Expected behavior**
No AssertError raised.

**Screenshots**
<img width="1520" alt="image" src="https://github.com/user-attachments/assets/be0eac04-7748-4ad2-9920-3c6395a611c3">

**Desktop**
 - OS:  macOS
 - Python version [e.g. 3.10.11]

**Potential Fix**
assert is_valid_probabilistic_grammar(self.grammar, self.start_symbol)

**Comment by andreas-zeller** [comment]
Thanks a lot! This is now fixed in the repository and will be part of the next code release.
