### ISSUE TITLE
Traffic stats for fuzzingbook.org

### ISSUE THREAD

**Issue by andreas-zeller** [uds-se/fuzzingbook#38]
Github traffic stats only cover the "proper" Github parts, not the pages hosted via Github pages (such as all of fuzzingbook.org).  Include Google analytics such that we can get an idea on our reader demographics, track which chapters are most popular, and inflate our egos proportionally to traffic.

**Comment by greshake** [comment]
Since Google Analytics was decided to be too data hungry, we now include a simple tracker that performs a static request for each chapter to log the amount of views. No data is stored on the user's browser, and no further information is logged.
