### ISSUE TITLE
Sample function to illustrate missing error checks seems to not fit its intention

### ISSUE THREAD

**Issue by ctsrc** [uds-se/fuzzingbook#41]
**Describe the bug**
In

* https://www.fuzzingbook.org/html/Fuzzer.html#Missing-Error-Checks
* https://github.com/uds-se/fuzzingbook/blob/6db8144c84aad76e92d0a84219f641aff31ede42/notebooks/Fuzzer.ipynb?short_path=016faee#L1061
* https://github.com/uds-se/fuzzingbook/blob/d3845db66cde014f4f80c415878b2203ab021bfb/docs/notebooks/Fuzzer.ipynb?short_path=9361d41#L1196

There is a function `char read_next_nonspace()`. The name of the function implies that it will return the next non-whitespace character, and the description of the function in the paragraph of text that precedes the code fragment says so too;

> Now assume a programmer is scanning the input for the next character, skipping space characters

The function itself is implemented as:

```c
char read_next_nonspace() {
    char lastc;

    do {
        lastc = getchar();
    } while (lastc != ' ');

    return (lastc);
}
```

The next paragraph of text goes on to say:

> What happens if the input ends prematurely, as would perfectly be feasible with fuzzing? Well, getchar() returns EOF, and keeps on returning EOF when called again; so the code above simply enters an infinite loop.

In isolation, this latter paragraph is stating the truth; this function does indeed get stuck in an infinite loop whenever `getchar()` returns `EOF` to it.

However, if we look at what happens other than that, we see that `read_next_nonspace()` is actually returning the first space, if any, that it finds, and skipping non-space characters. This is opposite to what the name of the function and its description implies that the function should do.

The fix for that issue is to change the loop condition from `lastc != ' '` to `lastc == ' '`. Giving us:

```c
char read_next_nonspace() {
    char lastc;

    do {
        lastc = getchar();
    } while (lastc == ' ');

    return (lastc);
}
```

And with that we no longer get stuck on `EOF` either.

Furthermore it is my opinion that the bug-fixed implementation above is what the complete implementation of that function should look like, and that no handling of `EOF` should be done inside this function. Instead, `EOF` should be handled by code that makes use of `read_next_nonspace()`.

A complete program that makes use of the bug-fixed function can be implemented as

```c
#include <stdio.h>

char read_next_nonspace ()
{
  char lastc;

  do
  {
    lastc = getchar();
  } while (lastc == ' ');

  return (lastc);
}

int main ()
{
  char next_nonspace;

  while ((next_nonspace = read_next_nonspace()) != EOF)
  {
    putchar(next_nonspace);
  }
}
```

As such I would argue that the originally given code fragment was never a case of a missing error check to begin with, because the `EOF` handling does not belong in that function. We can view `read_next_nonspace()` as a sort of "stream filter" with its "stream source" connected within it that reads from stdin and filters out spaces. `EOF` is a sentinel value (and usually implemented as a macro that resolves to `-1`) of great importance when dealing with filters but its presence should not affect this filter itself.

We can see this even more clearly if we separate the the filter from its source.

Flipping things around a little bit we get something akin to this: https://github.com/ctsrc/sources-and-filters/blob/2936e6501ec6d1cadecfd61601728d9cd6c01e16/filter-space.c

With that we can then go on to chaining multiple filters together etc. And hopefully the compiler writer people will have written their compilers to optimize away the overhead of our nested function calls and pointer derefs ;)

Anyway, I digress. The point of the bug report was to say that I believe that the originally given example was not a case of missing error handling, and that a different code fragment needs to be written that will properly illustrate the issue.

**Comment by ctsrc** [comment]
I submitted the bug report a bit too soon. Spotted a portion of it that I need to edit.

**Comment by ctsrc** [comment]
(Edited the bug report to fix something.)

**Comment by andreas-zeller** [comment]
Thanks!  This is now fixed to:

### Missing Error Checks

Many programming languages do not have exceptions, but instead have functions return special **error codes** in exceptional circumstances.  The C function `getchar()`, for instance, normally returns a character from the standard input; if no input is available anymore, it returns the special value `EOF` (end of file).  Now assume a programmer is scanning the input for the next character, reading in characters with `getchar()` until a space character is read:
```c
while (getchar() != ' ') {
}
```
What happens if the input ends prematurely, as would perfectly be feasible with fuzzing?  Well, `getchar()` returns `EOF`, and keeps on returning `EOF` when called again; so the code above simply enters an infinite loop.
