### ISSUE TITLE
pip installation not working

### ISSUE THREAD

**Issue by maxjung96** [uds-se/fuzzingbook#42]
Hi,
I installed the python module both via pip manually
`pip install fuzzingbook`
and through the PyCharm GUI.

When I want to import something, e.g. the sample import
`from fuzzingbook.Fuzzer import RandomFuzzer`
I always receive
`ModuleNotFoundError: No module named 'fuzzingbook'`

I am running python 3.6

**Comment by andreas-zeller** [comment]
We do not advertise pip installation as is still at an experimental stage, mostly because keeping the pip packages in sync with weekly book releases is a major pain.  We will fix this once all chapters are in and the book is stable.

**Comment by andreas-zeller** [comment]
I just created a pip distribution fuzzingbook 0.0.4 which should include all necessary modules.  Please let me know if there are any issues.
