### ISSUE TITLE
Deadlink in README.md

### ISSUE THREAD

**Issue by darkrsw** [uds-se/fuzzingbook#47]
**Describe the bug**
There is a dead hyperlink.

**To Reproduce**
In readme,

"See the table of contents for those chapters that are already done."

A hyperlink in the sentence, https://github.com/uds-se/fuzzingbook/blob/master/00_Table_of_Contents.ipynb, is dead.

Regards,
Dongsun.

**Comment by andreas-zeller** [comment]
Thanks!  The README.md file now should be fixed.
