### ISSUE TITLE
WhenToStopFuzzing - code typo

### ISSUE THREAD

**Issue by NerusSkyhigh** [uds-se/fuzzingbook#48]
**Describe the bug**
In 'WhenToStopFuzzing' chapter there is a typo in the code. Basically when you build the k_book the last trigram is not taken in account

**To Reproduce**
1. Go to WhenToStopFuzzing notebook in the part where the k_book is created and add at the end the lines:
```
print(trigrams[-2])
print(k_book[trigrams[-2]])
print(trigrams[-1])
print(k_book[trigrams[-1]]) 
```
2. Execute the code
3. See error

**Expected behavior**
The k_book is supposed to contain the trigram

**Screenshots**
![image](https://user-images.githubusercontent.com/36740323/58015301-2ce38900-7afb-11e9-8100-12a344454196.png)

**Additional context**
The for loop should be corrected from
`for i in range(1, len(trigrams)):` 
to
`for i in range(1, len(trigrams)+1):'

I know that's only a typo, but I hope I helped more than bother you.

EDIT:
I noticed that if you act like that the normalization factor is ruined. The normalization factor should be corrected in
'log(1 + 1 / i) / log(26**3+1)'
as the last i value is 26**3+1 and not 26**3

**Comment by mboehme** [comment]
Nice catch! Thanks for reporting. This will take some time to be reflected at fuzzingbook.org
Feel free to report any other problems.
