### ISSUE TITLE
Search-Based Fuzzing: minor issues

### ISSUE THREAD

**Issue by 251** [uds-se/fuzzingbook#54]
**Typos/Grammar**
1. > We can use this distance value as out fitness function
2. neighbor vs. neighbour
3. > there is a gradient that takes is straight to an optimal solution
4. > the false distance of is 0 by definition
5. > it is possible that the same test executions a condition multiple times
6. > corresponding to the two conditions, and the and with which they are
7. > produce this instrumented varion
8. > Python provides API to
9. > for which first retrieve the
10. > The better the fitness value an individual
11. > small number of randomly chosen individual

Funny that the algorithm finds a unicode sequence that changes the output order for `"%s: %.4f"`:
> '\ua7e9\ue9e0\ue7de턤댪囿厠‐\ue0c5ﴌ': 2.9999

**Comment by vrthra** [comment]
Thank you for the reports. These were are fixed in commit: https://github.com/uds-se/fuzzingbook/commit/a2e49d320392e9fc42f5b3843abfb9d7a677172f
