### ISSUE TITLE
Mutation Analysis: minor issues

### ISSUE THREAD

**Issue by 251** [uds-se/fuzzingbook#55]
**Grammar/Typos**

1. > how one identify which
2. > Given a function gcd and two test cases evaluate,
3. > However, that that introduces
4. > assume that each token in the program have
5. > What if actually try to
6. > test cases that can detect a single change in isolation is
7. > output, Lines
8. > discoverd

This paragraph appears twice on the same page:
> The Mutator provides the base class for...

**Comment by vrthra** [comment]
Thank you for the bug report; the issues have been fixed in https://github.com/uds-se/fuzzingbook/commit/7aa6be11dddc9dd97334545e29fc548a7f640109
