### ISSUE TITLE
AFLFastSchedule uses global variable 'parser' instead of class variable 'self.parser'

### ISSUE THREAD

**Issue by s8chsteu** [uds-se/fuzzingbook#63]
In the function 

    def parsable(self, seed):
        """Returns the substring that is parsable"""
        table = self.parser.chart_parse(seed.data, parser.start_symbol()) 
        cols = [col for col in table if col.states]
        return seed.data[:len(cols)-1]

the global variable 'parser' is used instead of a class variable with the same name. 

In the book, this is not noticeable as 'parser' and 'self.parser' are initialized with the same object, but on import, this function returns the error that 'parser' is uninitialized.

**Comment by mboehme** [comment]
Fixed. Thanks!
