### ISSUE TITLE
Error loading uds-se/fuzzingbook/master!

### ISSUE THREAD

**Issue by jgaleotti** [uds-se/fuzzingbook#83]
**Describe the bug**
"Edit as notebok" fails to launch 

**To Reproduce**
1. Go to https://www.fuzzingbook.org/
2. Select "Edit as notebook"
3. After a minute, you will get "Error loading uds-se/fuzzingbook/master!"

Build log:
```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockernl0w_yge'...
Updating files: 100% (1314/1314), done.
HEAD is now at 1c04042a Fix: need some section after synopsis
fatal: No url found for submodule path 'beta/slides/reveal.js' in .gitmodules
Error during build: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 128.

```

**Comment by andreas-zeller** [comment]
Thanks! After updating the reveal.js packages, we had a misconfiguration of .gitmodules; this is now fixed.
