### ISSUE TITLE
Improved directed power schedule 

### ISSUE THREAD

**Issue by Mizari** [uds-se/fuzzingbook#86]
https://www.fuzzingbook.org/html/GreyboxFuzzer.html#Improved-Directed-Power-Schedule
In formulae we can see:
  d'(i,t) = d(i,t)- minD / maxD - minD (if maxD != minD)

but in python code it is reversed:
  seed.energy = ((max_dist - min_dist) / (seed.distance - min_dist))

looks like the python code is the correct one, since the less the distance the more the energy, which coincides with the purpose described higher of improving small distance seeds importance.

**Comment by mboehme** [comment]
Nice catch. Thanks! Fixed in PR #84.
