### ISSUE TITLE
Another bug in `my_sqrt` (minor/fun)

### ISSUE THREAD

**Issue by wilcoxjay** [uds-se/fuzzingbook#95]
**Describe the bug**
In the chapter "Introduction to Software Testing", `my_sqrt_fixed(float('inf'))` results in an infinite loop.

**Expected behavior**
If we create `my_sqrt_fixed_program`, it should probably check for infinity.

**Additional context**
I admit I discovered this mostly egged on by the sentence

> As I am writing this, I believe that my_sqrt_fixed(x) is a correct implementation...

And yes, I found the bug with a fuzzer 😛 .  So I'm submitting this mostly for fun, and to prove the point implicitly expressed by that sentence: there's always another bug.

I understand that fixing it probably muddies the story of this chapter more than it's worth, so feel free to close this issue without fixing :)

**Comment by andreas-zeller** [comment]
Thanks! I have added an extra exercise to address this.
